<?php

// Language definitions used in viewforum.php
$lang_forum = array(

'Forum subtitle'			=>	'%1$s in this forum with details of %2$s.',
'Search subtitle'			=>	'%1$s found with details of %2$s.',
'Topics'					=>	'Temos',
'topics'					=>	'temos',
'Reply'						=>	'Atsakyti',
'Replies'					=>	'Atsakymai',
'Forum'						=>	'Forumas',
'reply'						=>	'atsakymas',
'replies'					=>	'atsakymai',
'View'						=>	'Peržiūrėti',
'Views'						=>	'Peržiūrėjo',
'views'						=>	'peržiūrėjo',
'view'						=>	'peržiūrėti',
'Last post'					=>	'Paskutinė žinutė',
'last post'					=>	'paskutinė žinutė',
'Select topic'				=>	'Pasirinkite temą: %s.',
'No replies info'			=>	'Nėra atsakymo informacijos',
'No views info'				=>	'Nėra peržiūros informacijos',
'No lastpost info'			=>	'Nėra naujausios žinutės informacijos',
'by poster'					=>	'%s',
'Item status'				=>	'%s:',
'Topic starter'				=>	'%s',
'New posts'					=>	'Naujos žinutės',
'Topic navigation'			=>	'( %s )',
'Location'					=>	'Rasta forume: %s',
'Pages'						=>	'Puslapiai',
'Post topic'				=>	'Sukurti naują temą',
'Login to post'				=>	'Jums reikia %1$s arba %2$s norint sukurti naują temą',
'No permission'				=>	'Atsiprašome, jūs neturite teisių kurti naują temą',
'Moved'						=>	'Perkeltą',
'Sticky'					=>	'Dažna tema',
'Closed'					=>	'Uždaryta',
'Empty forum'				=>	'Tuščias forumas',
'No topics'					=>	'Nėra temų',
'First topic nag'			=>	'Pirmasis sukurk temą.',
'You posted indicator'		=>	'·',
'Permalink forum'			=>	'Pastovi forumo nuoroda.',
'Forum options'				=>	'Forumo nustatymai',
'Moderate forum'			=>	'Moderuoti forumą',
'Mark forum read'			=>	'Pažymėti forumus kaip perskaitytus',
'RSS forum feed'			=>	'Forumo RSS srautas',
'New posts info'			=>	'Peržiūrėti pirmąją naują žinutę nuo paskutinio apsilankymo.'

);
