<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'No search permission'		=>	'Jūs neturitę privilegijų reikalingų naudotis paieška.',
'Search heading'			=>	'Vykdyti paiešką pagal jūsų kriterijus',
'Search flood'				=>	'Paiešką galima vykdyti nedažniau, kaip %s sekundės. Prašome truputį palaukti prieš vykdant naują paiešką.',
'Search legend'				=>	'Paieškos sąlygos',
'Results legend'			=>	'Paieškos rezultatai',
'Keywords info'				=>	'Galite ieškoti vieno raktažodžio arba keletos raktažodžių atskirtų tarpais.',
'Refine info'				=>	'Galite naudoti loginius operatorius <strong>AND</strong>, <strong>OR</strong> ir <strong>NOT</strong> norėdami gauti tikslesnius rezultatus.',
'Wildcard info'				=>	'Galima naudoti <strong>*</strong> vykdant paiešką pagal dalį raktažodžio ar prisijungimo vardo.',
'Forum default info'		=>	'Standartiškai paieška vykdoma visuose forumuose. Jūs galite susiaurinti paiešką pasirinkdami vieną ar daugiau forumų, kuriuose bus ieškoma.',
'Forum require info'		=>	'Jūs galite ieškoti viename ar daugiau forumų. Jūs <strong>privalote</strong> pasirinkti bent vieną forumą, kuriame vykdyti paiešką.',
'Keyword search'			=>	'Paieškos frazė',
'Author search'				=>	'Autoriaus vartotojo vardas',
'Forum search'				=>	'Ieškoti tik pasirinktuose forumuose',
'Forum search default'		=>	'Jeigu nepasirinkote nei vieno forumo, tai paieška bus vykdoma visuose.',
'Forum search require'		=>	'Privalote pasirinkti bent vieną forumą, kuriame bus vykdoma paieška.',
'Sort by'					=>	'Rezultatus rūšiuoti pagal',
'Sort order'				=>	'Rezultatų rūšiavimo tvarka',
'Sort by post time'			=>	'Sukūrimo laiką',
'Sort by author'			=>	'Autorių',
'Sort by subject'			=>	'Antraštę',
'Sort by forum'				=>	'Forumą',
'Ascending'					=>	'Didėjanti',
'Descending'				=>	'Mažėjanti',
'Display results'			=>	'Rodyti rezultatus',
'Show as topics'			=>	'kaip temas',
'Show as posts'				=>	'kaip žinutes',
'Submit search'				=>	'Vykdyti paiešką',
'User defined search'		=>	'Vartotojo nurodytą paieška',
'Search in'					=>	'Ieškoti',
'Message and subject'		=>	'Žinutės tekste ir temos pavadinime',
'Message only'				=>	'Tik žinutės tekste',
'Topic only'				=>	'Tik temos pavadinime',

// Results
'Search results'			=>	'Paieškos rezultatai',
'Topics with new'			=>	'Temos su naujomis žinutėmis',
'Recently active topics'	=>	'Paskutiniu metu aktyvios temos',
'Unanswered topics'			=>	'Neatsakytos temos',
'Subscriptions'				=>	'Prenumerata',
'Topics found'				=>	'Rasta temų',
'Posts found'				=>	'Rasta žinučių',
'Topics by'					=>	'Temų autorius %s',
'Posts by'					=>	'Žinučių autorius %s',
'Topics by user'			=>	'Šio vartotojo temos',
'Posts by user'				=>	'Šio vartotojo žinutės',
'Perform new search'		=>	'Vykdyti naują paiešką',
'Search options'			=>	'Paieškos nustatymai',
'Posted in'					=>	'Parašyta skiltyje ',
'No terms'					=>	'Nurodykite bent vieną raktažodį ar autorių, kad būtų vykdoma paieška.',
'No hits'					=>	'Pagal jūsų nurodytus kriterijus rezultatų nerasta.',
'No user posts'				=>	'Nurodytas vartotojas nerašė žinučių į pasirinktą forumą.',
'No user topics'			=>	'Nurodytas vartotojas nesukūrė temų pasirinktame forume.',
'No subscriptions'			=>	'Nėra prenumeruojamų temų.',
'No new posts'				=>	'Nėra temų su naujomis žinutėmis, nuo jūsų paskutinio apsilankymo.',
'No recent posts'			=>	'Paskutiniuoju metu nebuvo parašyta naujų žinučių.',
'No unanswered'				=>	'Šiame forume nėra neatsakytų žinučių.',
'Go to post'				=>	'Peržiūrėti žinutę',
'Go to forum'				=>	'Peržiūrėti forumą',
'Go to topic'				=>	'Peržiūrėti temą',
'Go to profile'				=>	'Peržiūrėti %s vartotojo profilį'

);
